### ISSUE TITLE
displays.yml should be modifiable without breaking the build

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#504]
**ISSUE**
* Tufts wants to remove dark from the displays list and implement a separate dark archive server
* Given our refactor of single item create, it would be great to have "nowhwere" be the first option in the list.

**ACCEPTANCE**
- [ ]  The test suit passes with the PRODUCTION displays.yml below
- [ ] The test suite passes with the DARK displays.yml below
- [ ] I can add displays options in the future without breaking the build.

**PRODUCTION displays.yml**
```yaml
# config/authorities/displays.yml
terms:
  - term: 'nowhere'
  - term: 'dl'
  - term: 'trove'
  - term: 'tisch'
  - term: 'perseus'
  - term: 'elections'
```

**DARK displays.yml**
```yaml
# config/authorities/displays.yml
terms:
  - term: 'dark'
```
