### ISSUE TITLE
Update list of valid displays

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#544]
**ISSUE**
For the version of displays.yml that's used in production, Tufts wants to remove the 'dark' option since it will be running on it's own stack.  

Also, because of our refactor of single item create, it would be convenient to have 'nowhere' be the default / first item in the displays list, so that if I don't change anything, items get created with safe (non-public) defaults.

I would like the version of the file checked into the repo to reflect these changes.  This entails making any updates necessary to make the application work with the following displays.ml file:

**PRODUCTION displays.yml**
```yaml
# config/authorities/displays.yml
terms:
  - term: 'nowhere'
  - term: 'dl'
  - term: 'trove'
  - term: 'tisch'
  - term: 'perseus'
  - term: 'elections'
```
